version: '3.3'
services:

  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${FLASK_APP_DATABASE_DB}
      - POSTGRES_USER=${FLASK_APP_DATABASE_USER}
      - POSTGRES_PASSWORD=${FLASK_APP_DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  warehouse:
    image: bacebogo/warehouse:14
    restart: always
    environment:
      - FLASK_APP_DATABASE_HOST=db
      - FLASK_APP_DATABASE_PORT=5432
      - FLASK_APP_SECRET_KEY=${FLASK_APP_SECRET_KEY}
      - FLASK_APP_DATABASE_USER=${FLASK_APP_DATABASE_USER}
      - FLASK_APP_DATABASE_PASSWORD=${FLASK_APP_DATABASE_PASSWORD}
      - FLASK_APP_DATABASE_DB=${FLASK_APP_DATABASE_DB}
    ports:
      - '5001:5001'
    depends_on:
      - db

volumes:
  db:
    driver: local
